apiVersion: batch/v1
kind: CronJob
metadata:
  name: daily-updates-bot
spec:
  schedule: "0 17 * * *"  # Every day at 5 PM UTC
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: daily-updates-bot
              image: thisisyashgarg/daly-updates-bot:latest
              workingDir: /daily-updates-bot
              volumeMounts:
                - name: daily-updates-bot-config
                  mountPath: /root
                  readOnly: true
              resources:
                requests:
                  memory: "64Mi"
                  cpu: "100m"
                limits:
                  memory: "128Mi"
                  cpu: "200m"
          volumes:
            - name: daily-updates-bot-config
              secret:
                secretName: daily-updates-bot-config
          restartPolicy: OnFailure
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
